blogTitle = "Yuppies"
mastHead = "YUPPI.ES"
authorName = "Siddharth Jain"
shortName = "f0rr0"
linkPrefix = "/yuppies"
description =  "Yuppies by Siddharth Jain. Sid is web developer-designer specializing in modular systems..blah blah blah"
bio = "Written by <a href='/about/'>Siddharth Jain</a> who is a developer-designer specializing in modular design and functional programming. If your company needs a JavaScript ninja who slays up and down the stack, don't hesitate to <a href='mailto:sid26@ucla.edu'>hit him up!</a> Open sourced on <a href='//github.com/f0rr0/f0rr0.github.io' rel='noopener noreferrer' target='__blank'>Github</a>."
